spring:
  application:
    name: detection
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
    #instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8081