spring:
  application:
    name: detection
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    #instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://137.204.57.68:8761/eureka/
server:
  port: 8081